spring.application.name=servicio-control-stock
server.port=${PORT:8002}

# URL para PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



# Dialecto para Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.jdbc.lob.non.contextual_creation=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Esto es opcional pero ayuda a que no explote si Rabbit tarda en arrancar
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=3s
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
# 1. Si el mensaje falla, NO lo vuelvas a meter en la cola (fundamental para salir del loop)
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# 2. Configura reintentos para que no sea infinito
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

# 3. Opcional: ver más detalle si sigue fallando
logging.level.org.springframework.amqp.rabbit.listener=DEBUG