server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: api-principal-route
          uri: http://api-principal:8001
          predicates:
            - Path=/carritos/** , /categorias/** , /pedidos/**
              ,/productos/**,/usuarios/** ,/api/payments/**
        - id: stock-service-route
          uri: http://servidor-stock:8002
          predicates:
            - Path=/stock/** ,/deposito/**